import fs from 'node:fs/promises';
import path from 'node:path';
import {randomBytes} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
if(!process.argv.includes('--confirm'))throw Error('此命令会撤销当前掌机访问；确认后请使用 --confirm。');
const dir=new URL('./.local/',import.meta.url),next=randomBytes(32).toString('hex'),authPath=new URL('auth.conf',dir);
const original=await fs.readFile(authPath,'utf8');
if(!/Authorization: Bearer [A-Za-z0-9_-]+/.test(original))throw Error('配对配置不完整，没有改动凭据');
const updated=original.replace(/Authorization: Bearer [A-Za-z0-9_-]+/,'Authorization: Bearer '+next);
const bridgeFile=path.resolve(fileURLToPath(new URL('./bridge.mjs',import.meta.url)));
const psPath=bridgeFile.replaceAll("'","''");
const stop="Get-CimInstance Win32_Process -Filter \"Name='node.exe'\" | Where-Object {$_.CommandLine -and $_.CommandLine.Contains('"+psPath+"')} | ForEach-Object {Stop-Process -Id $_.ProcessId}";
await fs.writeFile(new URL('auth.conf.new',dir),updated,{mode:0o600});
await fs.writeFile(new URL('token.new',dir),next+'\n',{mode:0o600});
await fs.rename(new URL('auth.conf.new',dir),authPath);
await fs.rename(new URL('token.new',dir),new URL('token',dir));
execFileSync('powershell.exe',['-NoProfile','-Command',stop],{windowsHide:true,stdio:'ignore'});
console.log('旧掌机凭据已撤销。电脑常驻服务会自动恢复；重新连接需要通过 USB 修复配对。');